### ISSUE TITLE
how to define the interaction(attraction/repulsion) rules btw. phnotypes or btw. neighbors?

### ISSUE THREAD

**Issue by inyeopjang** [djimenezsanchez/NaroNet#3]
To train the model, how the labels (phenotypes, neighbors, interactions) could be defined in the raw dataset?

**Comment by djimenezsanchez** [comment]
Hi, 

In this model, phenotypes, neighborhoods, and their interactions (i.e., areas) are automatically learned from the images and the patient-level labels. However, the number of phenotypes, neighborhoods, and areas could be changed. To this end, change the parameters in DatasetParameters.py file, where the lines that must be changed are the following: 

- args['clusters1']: Number of phenotypes to be learned by NaroNet. Example: 10 (phenotypes).
- args['clusters2']: Number of neighborhoods to be learned by NaroNet. Example: 11 (neighborhoods).
- args['clusters3']: Number of areas to be learned by NaroNet. Example: 6 (areas).

Best,
Daniel
