### ISSUE TITLE
the image label of breast cancer

### ISSUE THREAD

**Issue by EmilyZou123** [djimenezsanchez/NaroNet#5]
Hi,is it able to provide the image label of breast cancer?

**Comment by djimenezsanchez** [comment]
Hi,You can download the dataset from the original publication: https://www.nature.com/articles/s41586-019-1876-x where data is stored in this repository: https://zenodo.org/record/3518284

**Comment by EmilyZou123** [comment]
Thanks for your reply ,but I wonder how I can get the following files:
![屏幕截图 2023-08-14 205046](https://github.com/djimenezsanchez/NaroNet/assets/117978342/168e21b3-f2fb-4b18-950a-564271eed1c7)

**Comment by djimenezsanchez** [comment]
You can create an image_labels.xlsx from the supplementary materials provided in the paper (https://www.nature.com/articles/s41586-019-1876-x), where each of the images has a corresponding label.
